export class TestNewContent {
  static newContentMap: Map<string, string> = new Map([
    ["1para", `Notwithstanding any provision to the contrary herein, the parties acknowledge and agree that all obligations arising under this section shall survive termination. The indemnifying party shall hold harmless the indemnified party from any and all claims, damages, and liabilities. Any waiver of the foregoing must be in writing and signed by an authorized representative of each party.`],
    ["2para", `The receiving party agrees to maintain the confidentiality of all proprietary information disclosed pursuant to this agreement for a period of no less than five years. Such information shall not be reproduced, distributed, or disclosed to any third party without prior written consent. Any breach of this obligation shall entitle the disclosing party to seek equitable relief in addition to any other available remedies.
Each party represents and warrants that it has the full power and authority to enter into this agreement and perform its obligations hereunder. The execution and delivery of this agreement does not conflict with any existing contractual obligations. These representations shall be deemed repeated on each date that services are rendered under this agreement.`],
    ["3para", `Subject to the terms and conditions set forth herein, the contractor shall perform all services in a professional and workmanlike manner consistent with generally accepted industry standards. The contractor shall devote such time and attention as is reasonably necessary to fulfill its obligations. All deliverables shall conform to the specifications set forth in the applicable statement of work.
In the event of any dispute arising out of or relating to this agreement, the parties shall first attempt to resolve such dispute through good-faith negotiation. If the dispute cannot be resolved within thirty days, either party may submit the matter to binding arbitration. The arbitration shall be conducted in accordance with the rules of the American Arbitration Association.
Neither party shall be liable for any failure or delay in performance to the extent caused by circumstances beyond its reasonable control, including acts of God, natural disasters, or government actions. The affected party shall provide prompt written notice describing the force majeure event and its expected duration. Upon cessation of the force majeure event, the affected party shall resume performance as soon as reasonably practicable.`],
  ]);
}
